services: 
    frontend: 
        container_name: app_client
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        env_file: 
            - ./frontend/.env
        ports:
            - ${CLIENT_PORT}:80
        environment:
            - REACT_APP_API_URL=${REACT_APP_API_URL}
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
          - backend
        networks:
            - app-network
    backend: 
        container_name: app_server
        build: 
            context: ./backend
            dockerfile: Dockerfile
        env_file: 
            - ./backend/.env
        ports: 
            - "${SERVER_PORT}:3001"
        environment: 
            - DATABASE_URL=${DATABASE_URL}
            - COUNTRIES_API_BASE_URL=${COUNTRIES_API_BASE_URL}
        volumes: 
            - ./backend:/app
            - /app/node_modules
        depends_on:
          - database
        networks:
            - app-network
    database:
        container_name: app_db
        image: postgres:14
        env_file: 
            - ./backend/.env
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS:-secret}
        volumes:
            - app-data:/var/lib/postgresql/data
        networks:
            - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app-data: